import { z } from 'zod';

// Validation schemas (Zod). Rules are declared once and the TypeScript types
// are derived from them, keeping validation and typing in sync.

export const generoSchema = z.enum(['masculino', 'femenino', 'otro']);

export const grupoSanguineoSchema = z.enum([
  'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-',
]);

// Payload accepted when creating a patient.
export const crearPacienteSchema = z.object({
  nombre: z.string().min(1, 'El nombre es obligatorio').max(100),
  apellidos: z.string().min(1, 'Los apellidos son obligatorios').max(150),
  email: z.string().email('Email no válido'),
  telefono: z.string().min(6, 'Teléfono no válido').max(20),
  fechaNacimiento: z
    .string()
    .refine((v) => !Number.isNaN(Date.parse(v)), 'Fecha de nacimiento no válida'),
  genero: generoSchema,
  grupoSanguineo: grupoSanguineoSchema.optional(),
  alergias: z.array(z.string()).default([]),
});

// On update every field is optional (PATCH-like semantics over PUT).
export const actualizarPacienteSchema = crearPacienteSchema.partial();

// Derived types.
export type CrearPacienteDTO = z.infer<typeof crearPacienteSchema>;
export type ActualizarPacienteDTO = z.infer<typeof actualizarPacienteSchema>;

// The entity type is generated by Prisma from the schema (single source of truth).
// createdAt/updatedAt are Date and get serialized to ISO strings by res.json().
export type { Paciente } from '@prisma/client';
